Feature/adminwebredo
sigdotcom/mstacm.org pull request #261
Opened 2020-05-31 22:20 UTC by cjwagn1

# Pull Request Description

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-06-28 07:01 UTC, ClayMav commented on apps/admin-web/src/screens/Events/Collapse.tsx
> +    },
Because you are doing display, I don't think this will have an animation, consider using size

2020-06-28 07:03 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/Graph.tsx
> +};
Add note that this is temporary placeholder data

2020-06-28 07:04 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +        <a onClick={() => setTitle("This week ")}>This week</a>
Don't use an anonymous function here

2020-06-28 07:05 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +        <a onClick={() => setTitle("This month ")}>This month</a>
Don't use an anonymous function here

2020-06-28 07:05 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +      </Menu.Item> */}
:(

2020-06-28 07:08 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +    [eventNumber, difference] = ThisWeekData();
capital T function name?

2020-06-28 07:08 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +  function ThisWeekData() {
function names should be camelCase

2020-06-28 07:09 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +          new Date(todaysISO.split("T")[0]).getDay() * 86400000
You can directly compare Date objects and get the delta

2020-06-28 07:09 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +          7 * 86400000
use Date object deltas instead of this

2020-06-28 07:10 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +        0
use date object deltas instead of this

2020-06-28 07:11 UTC, ClayMav commented on apps/admin-web/src/screens/Events/DataCards/NumberOfEventCard.tsx
> +    const lastMonthFilter = events.filter(
Can you create a variable for "time frame" and set it to be a number of days? then just make one filter function?

2020-06-28 07:15 UTC, ClayMav commented on apps/admin-web/src/screens/Events/EventList.tsx
> +];
??

2020-06-28 07:17 UTC, ClayMav commented on apps/admin-web/src/screens/Events/EventList.tsx
> +    );
can you take above advice to make one filter and create util function to use across app

2020-06-28 07:18 UTC, ClayMav commented on apps/admin-web/src/screens/Events/EventList.tsx
> +  const { loading, error, data }: any = useEventsQuery();
Instead of doing it this way, why not useevents query one time in the eventlist and pass the events for each in as props

2020-06-28 07:18 UTC, ClayMav commented on apps/admin-web/src/screens/Events/EventList.tsx
> +    const futureEventFilte = events.filter(
misspelled

2020-06-28 07:19 UTC, ClayMav commented on apps/admin-web/src/screens/redo/Main.tsx
> +// import { Event } from "./Eventss";
?

2020-06-28 07:20 UTC, ClayMav commented on apps/admin-web/src/screens/redo/Main.tsx
> +      <Route path="/events/previous" component={Previous} />
Can you route /events to /events/upcoming

2020-06-28 07:51 UTC, ClayMav commented
Also the location seems to get merged with the link to the event which doesnt make sense in this case. The edit and remove buttons should probably be held to the bottom of the card to keep it consistent for the user

2020-08-20 05:13 UTC, ClayMav commented
Any progress here?

2020-08-24 02:52 UTC, cjwagn1 commented
Hopefully, this push agrees with you a little bit more, Clay. I tried my best. There were a lot of changes and I rewrote some old components to be reusable. Some things may have gotten past. I tested the best I could but there's always room for improvement. 

Somethings I could not replicate that you had problems were:

- "Event rendering is broken if the flier is not present" 
- "sample events in attached photo break all things"
- "styling on number of events is just busted"

Thought I could not replicate these, I put a fix for them that could solve the issues you encountered. 

The things I ended up not addressing was dealing with the time deltas/util functions for the filter. The reason being is because I think there is a better way to do it overall and want to redo it later. For now, it works and as long as there are no major performance problems with the way I did it, I did not see the issue. Note: I do want to improve it, I just need to learn a little bit more before I attempt it again.

Hope you like it!

2020-09-10 21:05 UTC, ClayMav commented
Switch to getCurrentEvents for upcoming events' query so that the performance is good on at least the upcoming page. We will still see performance hits on past events as the events grow but not really sure how to help with that for now without pagination

2020-09-22 02:27 UTC, ClayMav requested changes
I will run the code and give that feedback, but some code changes still required

2020-09-22 02:27 UTC, ClayMav commented on apps/admin-web/src/tools/Tools.tsx
> +        <ToolBox link="/events/upcoming" tool="Events" />
no previous?

2020-10-05 07:48 UTC, ClayMav commented
@cjwagn1 lets get this baby cleaned up and merged

2020-10-08 00:37 UTC, cjwagn1 commented on apps/admin-web/src/screens/Events/EventList.tsx
> +  data: any;
😐

2022-08-20 05:56 UTC, closed without merging