Feature/quick access
sigdotcom/mstacm.org pull request #293
Opened 2020-09-27 19:57 UTC by NickFuller24

# Pull Request Description

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-03 03:15 UTC, ClayMav commented
Awesome work, Nick.

Hopefully the review comes through quick. In the meantime - @all-contributors please add @NickFuller24 for code

2020-10-03 05:38 UTC, KerimD requested changes

2020-10-03 05:38 UTC, KerimD commented on apps/profile-web/src/components/QuickAccess/index.tsx
> +          <svg transform="translate(9.25)" width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
Use Eva Icons for the three link icons here.

2020-10-03 05:38 UTC, KerimD commented on apps/profile-web/src/components/QuickAccess/index.tsx
> +        <QAItem href = "https://google.com">
```suggestion
        <QAItem href="https://google.com">
```
Run Prettier so you don't have extra white space.

2020-10-05 19:03 UTC, KerimD approved these changes

2020-10-05 19:05 UTC, merged